server:
  port: 8089

#关闭thymeleaf缓存，使得变更后页面能够及时加载
spring:
  thymeleaf:
    cache: false
#  datasource:
#    driver-class-name: oracle.jdbc.OracleDriver
##    url: jdbc:oracle:thin:@10.225.0.176:1521:orcl
#    url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
#    username: krdt
#    password: 1
  servlet:
    multipart:
      maxFileSize: 100MB
      max-request-size: 150MB


